# PNN 插件配置文件
# 作者: 柠枺
# 源代码由AI提供，无法保证稳定性！

#-------------------------------
#              ==插件基础配置==
#-------------------------------

# 是否启用昵称占位符支持
# 启用后：
# 1. 可以在昵称中使用其他插件的占位符（需安装PlaceholderAPI）
# 2. 其他插件也可以使用PNN提供的占位符
# 默认: true（启用）
placeholder: false

# 昵称屏蔽词列表
# 玩家无法使用包含这些词语的昵称
Block-words:
  - sb
  - 傻逼
  # 可以根据需要添加更多屏蔽词

#-------------------------------
#              ==昵称设置==
#-------------------------------

# 昵称最大长度，超过此长度将被拒绝
# 默认: 32个字符
max-nickname-length: 32

# 昵称是否允许使用颜色代码(&)
# 例如: &c将显示为红色文字
# 默认: true（允许）
allow-colors: true

# 昵称是否允许使用格式代码(&k, &l, &m, &n, &o, &r)
# 例如: &l将显示为粗体文字
# 默认: true（允许）
allow-formats: true

#-------------------------------
#              ==聊天格式配置==
#-------------------------------

# 是否覆盖默认聊天格式
# true: 使用下方自定义的聊天格式
# false: 保持服务器默认聊天格式，只替换玩家名为昵称
# 默认: false（不覆盖）
override-chat-format: false

# 聊天格式相关配置
# 仅在override-chat-format为true时生效
chat-format:
  # 普通聊天消息格式
  # 可用占位符:
  # %pnn% - 玩家昵称
  # %player% - 玩家真实ID
  # %msg% - 聊天内容
  # %world% - 玩家所在世界
  # 在启用PlaceholderAPI后还可使用其他插件的占位符
  format: "&7[&r%pnn%&7] &f%msg%"
  
  # 玩家加入服务器消息格式
  # 设置为空字符串("")将禁用加入消息
  # 默认: "&e%pnn% 加入了游戏"
  join-message: "&e%pnn% 加入了游戏"
  
  # 玩家离开服务器消息格式
  # 设置为空字符串("")将禁用离开消息
  # 默认: "&e%pnn% 离开了游戏"
  quit-message: "&e%pnn% 离开了游戏"
  
  # 聊天颜色权限控制
  # true: 只有拥有pnn.chatcolor权限的玩家才能在聊天中使用颜色代码
  # false: 所有玩家都可以在聊天中使用颜色代码
  # 默认: true（需要权限）
  color-permission: true

#-------------------------------
#              ==数据存储配置==
#-------------------------------

# 数据保存模式
# 目前仅支持: yaml
# 默认: yaml
data-saving-mode: yaml

#-------------------------------
#              ==占位符说明==
#-------------------------------

# PNN提供的占位符(需安装PlaceholderAPI):
# %pnn_nickname% - 玩家的昵称
# %pnn_has_nickname% - 玩家是否有昵称(返回true或false)
# %pnn_real_name% - 玩家的真实ID
#
# 聊天消息和加入/退出消息中可直接使用的占位符:
# %pnn% - 玩家的昵称(如无昵称则显示真实ID)