# PNN 插件配置文件
# 作者: 柠枺
# 源代码由AI提供，无法保证稳定性！

#-------------------------------
#              ==插件基础配置==
#-------------------------------

# 是否启用昵称占位符支持
# 启用后：
# 1. 可以在昵称中使用其他插件的占位符（需安装PlaceholderAPI）
# 2. 其他插件也可以使用PNN提供的占位符
# 默认: false（不启用）
placeholder: false

# 占位符显示格式配置
# 可用变量:
# {nickname} - 玩家的昵称（如果有）
# {player} - 玩家的真实ID
placeholder-format:
  # %pnn% 占位符的默认显示格式（用于聊天和加入/退出消息）
  # 默认: {nickname}（直接显示昵称，如果没有昵称则显示真实ID）
  pnn-format: "{nickname}"
  
  # %pnn_nickname% 占位符的默认显示格式（PlaceholderAPI）
  # 默认: {nickname}（直接显示昵称，如果没有昵称则显示真实ID）
  pnn-nickname-format: "{nickname}"

# 昵称屏蔽词列表
# 玩家无法使用包含这些词语的昵称
Block-words:
  - sb
  - 傻逼
  # 可以根据需要添加更多屏蔽词

# 经济系统配置
economy:
  # 是否启用经济系统
  enabled: false
  # 设置昵称的费用
  set-nickname-cost: 100.0
  # 重置昵称的费用
  reset-nickname-cost: 50.0
  # 是否在设置/重置昵称时返还部分费用
  refund-on-reset: true
  # 返还比例 (0.0-1.0)
  refund-ratio: 0.5

#-------------------------------
#              ==昵称设置==
#-------------------------------

# 昵称最大长度，超过此长度将被拒绝
# 默认: 32个字符
max-nickname-length: 32

# 昵称是否允许使用颜色代码(&)
# 例如: &c将显示为红色文字
# 默认: true（允许）
allow-colors: true

# 昵称是否允许使用格式代码(&k, &l, &m, &n, &o, &r)
# 例如: &l将显示为粗体文字
# 默认: true（允许）
allow-formats: true

#-------------------------------
#              ==显示设置==
#-------------------------------

# 是否设置玩家的DisplayName
# true: 设置玩家的显示名称为昵称
# false: 不修改玩家的显示名称，但可能会导致聊天中昵称显示不正常
# 注意: 一些插件依赖DisplayName来显示玩家名称
# 默认: false（设置）
set-display-name: false

# 是否单独覆盖TAB列表中的名称格式
# true: 使用下方自定义的TAB列表格式
# false: 保持服务器默认TAB列表格式
# 注意: 如果override-chat-format为true，此选项无效（将总是覆盖）
# 默认: false（不覆盖，但如果override-chat-format为true则仍会覆盖）
override-tab-format: false

# TAB列表中的名称格式
# 仅在override-tab-format为true或override-chat-format为true时生效
# 可用占位符:
# %pnn% - 玩家昵称
# %player% - 玩家真实ID
# 默认: "&7[&r%pnn%&7] %player%"
tab-format: "&7[&r%pnn%&7] %player%"

#-------------------------------
#              ==聊天格式配置==
#-------------------------------

# 是否完全覆盖原版/其他插件的聊天与显示格式
# true: 使用下方自定义的聊天格式，修改TAB列表名称，完全接管聊天显示
# false: 保持服务器默认聊天格式，只通过DisplayName影响聊天中的名称，不更改TAB列表
# 注意: 即使设为false，如果set-display-name为true，玩家的显示名称(DisplayName)仍会更改
# 默认: false（不覆盖）
override-chat-format: true

# 聊天格式相关配置
# 仅在override-chat-format为true时生效
chat-format:
  # 普通聊天消息格式
  # 可用占位符:
  # %pnn% - 玩家昵称
  # %player% - 玩家真实ID
  # %msg% - 聊天内容
  # %world% - 玩家所在世界
  # 在启用PlaceholderAPI后还可使用其他插件的占位符
  format: "&7[&r%pnn%&7]<%player%> &f%msg%"
  
  # 玩家加入服务器消息格式
  # 设置为空字符串("")将禁用加入消息
  # 默认: "&e%pnn% 加入了游戏"
  join-message: "&e%pnn% 加入了游戏"
  
  # 玩家离开服务器消息格式
  # 设置为空字符串("")将禁用离开消息
  # 默认: "&e%pnn% 离开了游戏"
  quit-message: "&e%pnn% 离开了游戏"
  
  # 聊天颜色权限控制
  # true: 只有拥有pnn.chatcolor权限的玩家才能在聊天中使用颜色代码
  # false: 所有玩家都可以在聊天中使用颜色代码
  # 注意: 仅在override-chat-format为true时生效
  # 默认: true（需要权限）
  color-permission: true

#-------------------------------
#              ==数据存储配置==
#-------------------------------

# 数据保存模式
# 目前仅支持: yaml
# 默认: yaml
data-saving-mode: yaml

#-------------------------------
#              ==占位符说明==
#-------------------------------

# PNN提供的占位符(需安装PlaceholderAPI):
# %pnn_nickname% - 玩家的昵称
# %pnn_has_nickname% - 玩家是否有昵称(返回true或false)
# %pnn_real_name% - 玩家的真实ID
#
# 聊天消息和加入/退出消息中可直接使用的占位符:
# %pnn% - 玩家的昵称(如无昵称则显示真实ID)