name: PNN发布流程

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: 设置JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: 获取版本信息
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: 使用Maven构建
      run: mvn -B package --file pom.xml
      
    - name: 重命名构建产物
      run: |
        mkdir -p target/artifacts
        cp target/pnn-*.jar target/artifacts/PNN-${{ steps.get_version.outputs.VERSION }}.jar
      
    - name: 创建GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v4
      with:
        name: PNN ${{ steps.get_version.outputs.VERSION }}
        files: target/artifacts/PNN-${{ steps.get_version.outputs.VERSION }}.jar
        draft: false
        prerelease: false
        generate_release_notes: true 